# Fly.io Configuration for TX Backend
app = "tx-backend-production"
primary_region = "ams" # Amsterdam (close to Europe)

[build]
  image = "jeanpaulkadusimanegaberobert1/tx-backend:v1.0.3-20251018-225528"

[env]
  ENVIRONMENT = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "tx_data"
  destination = "/app/data"
