services:
- type: web
  name: tx-predictive-intelligence
  env: python
  plan: free
  buildCommand: |
    pip install -r requirements.txt
  startCommand: |
    gunicorn --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 120 --access-logfile - --error-logfile - --log-level debug wsgi:app
  envVars:
    - key: PORT
      value: 9000
  healthCheckPath: /health