services:
- type: web
  name: tx-copilot-bot
  env: python
  plan: free
  region: uganda  # Optional: Set nearest to your users
  buildCommand: |
    pip install -r requirements.txt
  startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --access-logfile - --error-logfile - wsgi:app
  envVars:
    - key: PORT
      value: 10000
  healthCheckPath: /health
  autoDeploy: true