services:
- type: web
  name: tx-copilot-bot
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: python wsgi.py
  envVars:
    - key: PORT
      value: 10000
  healthCheckPath: /health