services:
- type: web
  name: tx-backend
  env: python
  plan: starter
  buildCommand: |
    pip install -r requirements.txt
  startCommand: |
    python main.py
  healthCheckPath: /api/status
  envVars:
    - key: PORT
      value: 5000
    - key: FLASK_ENV
      value: production
    - key: BACKEND_SCAN_INTERVAL
      value: 120
    - key: ALERT_CONFIDENCE_THRESHOLD
      value: 0.85
    - key: ENABLE_PAPER_TRADING
      value: true