# render.yaml
services:
  - type: web
    name: tx-copilot-bot
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 wsgi:app
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000