services:
- type: web
  name: tx-backend
  env: python
  plan: starter
  buildCommand: |
    pip install -r requirements.txt
  startCommand: |
    gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 -b 0.0.0.0:$PORT main:app
  healthCheckPath: /health
  envVars:
    - key: FLASK_ENV
      value: production
    - key: CORS_ORIGINS
      value: https://tx-figma-frontend.onrender.com,http://localhost:3000,http://localhost:5173
    - key: BACKEND_SCAN_INTERVAL
      value: 180
    - key: ALERT_CONFIDENCE_THRESHOLD
      value: 0.85
    - key: ENABLE_PAPER_TRADING
      value: true